# Diagnostic Client library
# Copyright (C) 2023  Avijit Dey
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
variables:
  DOCKER_IMAGE: "registry.gitlab.com/iandiehard/dev_build_env"
  DOCKER_IMAGE_TAG: "latest"
  BUILD_TYPE: Debug

image: $DOCKER_IMAGE:$DOCKER_IMAGE_TAG
stages:
  - prepare          
  - build
  - test
  - deploy

prepare-job:
  stage: prepare
  rules:
    - if: '$CI_MERGE_REQUEST_LABELS =~ /run_full_pipeline/'
      when: always
    - when: never
  script:
    - echo "Create "build" folder..."
    - mkdir build

build-job:       
  stage: build
  rules:
    - if: '$CI_MERGE_REQUEST_LABELS =~ /run_full_pipeline/'
      when: always
    - when: never
  script:
    - echo "Empty building..."

component-test-job:  
  stage: test
  rules:
    - if: '$CI_MERGE_REQUEST_LABELS =~ /run_full_pipeline/'
      when: always
    - when: never
  script:
    - echo "Set-up the network..."
    - sh .devcontainer/post_start.sh
    - echo "Configure CMake..."
    - cmake -B build -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_WITH_DLT:BOOL=ON -DBUILD_WITH_TEST:BOOL=ON -DBUILD_DOXYGEN:BOOL=ON -DBUILD_SHARED_LIBS:BOOL=OFF -DBUILD_EXAMPLES:BOOL=ON -DCMAKE_INSTALL_PREFIX:PATH=build/install
    - echo "Start Building..."
    - cmake --build build --config $BUILD_TYPE
    - echo "Running unit tests..."
    - echo "Print DLT messages..."
    - export DLT_LOCAL_PRINT_MODE=FORCE_ON
    - export DLT_INITIAL_LOG_LEVEL="::6"
    - echo "Start Test..."
    - cd build/test
    - ./gtest-diag-client-lib --gtest_output="xml:report.xml"
  artifacts:
    when: always
    reports:
      junit: build/test/report.xml

deploy-job:
  stage: deploy
  rules:
    - if: '$CI_MERGE_REQUEST_LABELS =~ /run_full_pipeline/'
      when: always
    - when: never
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
