# Diagnostic Client library
# Copyright (C) 2022  Avijit Dey
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
variables:
  DOCKER_IMAGE: "registry.gitlab.com/iandiehard/dev_build_env"
  DOCKER_IMAGE_TAG: "feature-docker-image-to-docker-hub"
  BUILD_TYPE: Debug

image: $DOCKER_IMAGE:$DOCKER_IMAGE_TAG
stages:
  - prepare          
  - build
  - test
  - deploy

prepare-job:
  stage: prepare
  script:
    - echo "Create "build" folder..."
    - mkdir build

build-job:       
  stage: build
  script:
    - echo "Empty building..."

component-test-job:  
  stage: test
  script:
    - echo "Set-up the network..."
    - sh .devcontainer/post_start.sh
    - echo "Configure CMake..."
    - cmake -B build -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_INSTALL_PREFIX:PATH=build/install
    - echo "Start Building..."
    - cmake --build build --config $BUILD_TYPE
    - echo "Running unit tests..."
    - sleep 60
    - echo "Print DLT messages..."
    - export DLT_LOCAL_PRINT_MODE=FORCE_ON
    - echo "Start Test..."
    - cd build/test
    - ./gtest-diag-client-lib --gtest_output="xml:report.xml"
  artifacts:
    when: always
    reports:
      junit: report.xml

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
